# Generated by Django 3.1.7 on 2021-02-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(default='media/img/repartidor/defaultUser.png', upload_to='media/img/repartidor')),
                ('tydoc', models.CharField(blank=True, choices=[('CC', 'CC'), ('Passport', 'Passport'), ('Otro', 'Otro')], default='CC', max_length=10, null=True)),
                ('cedulaId', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('phoneNum', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modify', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
